In [2]:
import simplejson as json
import tweepy
import pandas as pd

In [3]:
consumer_key = "rZHTEq46hi52VQa2SZWWkPkaU"
consumer_secret = "kRitehlcvrpzm0vBNVZZlThNDfeEkOak9tFNauyA3NeThPGQfa"
access_key = "1114828359148691458-l7idVW5D3DoRpDojNkS5iNWK5OSC99"
access_secret = "GDQKOhEbzOODGSOyw1DALpXdHKceaKJgKQhMl81RjviIA"

In [4]:
def streaming_tweets(handler,file_name): 
              
        
    # Authorization to for twitter api
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret) 
  
    # Access usnig uset access credentials
    auth.set_access_token(access_key, access_secret) 
  
    # Calling API function
    api = tweepy.API(auth) 
        
    # Maximum Number of tweeets we want to extract
    number_of_tweets=10000
        
    # Required tweets        
    tweets = api.user_timeline(screen_name=handler,count =number_of_tweets)
        
    # Dumping tweets into json file
    for tweet in tweets:
        with open(file_name, 'a', encoding='utf8') as file:
            file.write(json.dumps(tweet._json))   
            file.write('\n')
        
# Function Calling
streaming_tweets("@midasIIITD",'tweets.json')

In [8]:
def show_tweets(file_name):
   

    # Opening json file     
    tweets_file = open(file_name, "r",encoding='utf8')
    tweets_file.seek(0, 0)
    
    # Tweets data for all tweets     
    tweets_data = []
    
    # Iterating over all lines in tweets_filename   
    for line in tweets_file.readlines():
        try:
            # Read in one line of the file, convert it into a json object 
            tweet = json.loads(line)
            
            temp = []
            if 'text' in tweet: # only messages contains 'text' field is a tweet
                temp.append(tweet['text'])
                temp.append(tweet['created_at'])
                temp.append(tweet['favorite_count'])
                temp.append(tweet['retweet_count'])
                img_count = 0
                try:
                    for media in tweet['entities']['media']:
                        if media['type'] == 'photo':
                            img_count += 1
                except:
                    pass
                if(img_count==0):
                    img_count = None
                temp.append(img_count)
                tweets_data.append(temp)

        except:
            # read in a line is not in JSON format (sometimes error occured)
            continue
            
    # Closing file Handle                   
    tweets_file.close()
    
    # Converting into pandas dataframe
    df = pd.DataFrame(tweets_data)
    df.columns = ["Text", "Date and Time", "Likes/Favourite", "Retweet Count","Images Count"]
    return df

In [9]:
filename = 'tweets.json'
table = show_tweets(filename)
table

,Text,Date and Time,Likes/Favourite,Retweet Count,Images Count
0,RT @IIITDelhi: We are delighted to share that ...,Tue Apr 09 16:45:07 +0000 2019,0,8,NaN
1,RT @Harvard: Professor Jelani Nelson founded A...,Tue Apr 09 05:04:27 +0000 2019,0,35,NaN
2,RT @emnlp2019: For anyone interested in submit...,Tue Apr 09 05:04:11 +0000 2019,0,12,NaN
3,RT @multimediaeval: Announcing the 2019 MediaE...,Mon Apr 08 19:38:09 +0000 2019,0,15,NaN
4,"Many Congratulations to @midasIIITD student, S...",Mon Apr 08 07:08:12 +0000 2019,14,2,NaN
5,@midasIIITD thanks all students who have appea...,Mon Apr 08 03:27:42 +0000 2019,5,0,NaN
6,"@himanchalchandr Meanwhile, complete CV/NLP ta...",Sun Apr 07 14:17:29 +0000 2019,0,0,NaN
7,@sayangdipto123 Submit as per the guideline ag...,Sun Apr 07 14:17:09 +0000 2019,0,0,NaN
8,We request all students whose interview are sc...,Sun Apr 07 11:43:24 +0000 2019,1,1,NaN
9,"Other queries: ""none of the Tweeter Apis give ...",Sun Apr 07 06:55:19 +0000 2019,5,2,NaN
10,"Other queries: ""do we have to make two differe...",Sun Apr 07 06:53:38 +0000 2019,4,1,NaN
11,"Other queries: ""If using Twitter api, it does ...",Sun Apr 07 05:32:27 +0000 2019,6,1,NaN
12,Response to some queries asked by students on ...,Sun Apr 07 05:29:40 +0000 2019,7,1,NaN
13,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,Sat Apr 06 17:11:29 +0000 2019,0,2,NaN
14,@nupur_baghel @PennDATS Congratulation @nupur_...,Sat Apr 06 16:43:27 +0000 2019,18,3,NaN
15,We have emailed the task details to all candid...,Fri Apr 05 16:08:37 +0000 2019,11,1,NaN
16,RT @rfpvjr: Our NAACL paper on polarization in...,Fri Apr 05 04:05:11 +0000 2019,0,16,NaN
17,RT @kdnuggets: Effective Transfer Learning For...,Fri Apr 05 04:04:43 +0000 2019,0,11,1.0
18,RT @stanfordnlp: What’s new in @Stanford CS224...,Wed Apr 03 18:31:53 +0000 2019,0,59,NaN
19,RT @DeepMindAI: Today we're releasing a large-...,Wed Apr 03 17:04:32 +0000 2019,0,870,NaN
20,RT @ylecun: Congratulations Jitendra Malik !\n...,Wed Apr 03 09:03:40 +0000 2019,0,16,NaN
21,RT @IIITDelhi: Another chance to take admissio...,Wed Apr 03 07:46:02 +0000 2019,0,4,NaN
22,Dear @midasIIITD internship candidates who hav...,Tue Apr 02 04:20:13 +0000 2019,8,1,NaN
23,Looking forward to your paper submission to @I...,Tue Apr 02 02:44:54 +0000 2019,5,1,NaN
24,RT @ngrams: Reproducibility in multimedia rese...,Tue Apr 02 02:35:44 +0000 2019,0,7,NaN
25,Online application for https://t.co/DJFDrQsHZP...,Mon Apr 01 06:53:08 +0000 2019,7,2,NaN
26,RT @ACMMM19: A final reminder of the Reproduci...,Sun Mar 31 10:21:24 +0000 2019,0,10,NaN
27,RT @isarth23: Thanks for the support and help ...,Fri Mar 29 19:43:24 +0000 2019,0,2,NaN
28,"Since SemEval-2019 will be held June 6-7, 2019...",Fri Mar 29 17:16:40 +0000 2019,9,1,NaN
29,+@aggarwal_kartik.\nCongrats! Wish you many mo...,Fri Mar 29 17:04:30 +0000 2019,2,0,NaN
...,...,...,...,...,...
370,RT @RatnRajiv: Fortunate to have appreciation ...,Thu Jan 10 08:48:17 +0000 2019,0,3,NaN
371,RT @Harvard: The study provides potential futu...,Wed Jan 09 02:05:06 +0000 2019,0,9,NaN
372,RT @UniofOxford: In the final episode of serie...,Mon Jan 07 09:05:12 +0000 2019,0,16,NaN
373,@ACMMM19: Call for Workshop Proposals \n\nDead...,Sun Jan 06 12:54:06 +0000 2019,1,0,NaN
374,@ACMMM19: Call for Grand Challenge Proposals\n...,Sun Jan 06 04:29:25 +0000 2019,1,0,NaN
375,"Since 1993, ACM Multimedia has been bringing t...",Sun Jan 06 04:09:54 +0000 2019,5,1,NaN
376,@ACMMM19 is structured around four themes (alp...,Sun Jan 06 04:07:29 +0000 2019,1,0,NaN
377,ACM Multimedia 2019: First Call for Papers/Cal...,Sun Jan 06 04:05:38 +0000 2019,4,2,NaN
378,RT @ACMMM19: Happy new year! 2019 started with...,Thu Jan 03 06:14:05 +0000 2019,0,2,NaN
379,You may follow @midasIIITD updates through fol...,Tue Jan 01 17:21:49 +0000 2019,4,2,NaN
380,"Today, @midasIIITD completed one year at @IIIT...",Tue Jan 01 17:17:56 +0000 2019,14,5,NaN
381,RT @debanjanbhucs: Happy anniversary to @midas...,Tue Jan 01 16:14:24 +0000 2019,0,4,NaN
382,Two Research Assistant (RA) positions are stil...,Thu Dec 27 10:28:31 +0000 2018,2,1,NaN
383,Positions for two Research Assistants (RA) are...,Thu Dec 27 09:59:06 +0000 2018,5,3,NaN
384,RT @TCoolsIT: I wrote a blogpost on CoreNLP hi...,Thu Dec 27 02:33:58 +0000 2018,0,12,NaN
385,@RatnRajiv delivered a research talk at the Ce...,Wed Dec 26 09:41:04 +0000 2018,14,2,NaN
386,@midasIIITD look forward to work together. htt...,Tue Dec 25 04:15:15 +0000 2018,1,0,NaN
387,"@the_dhumketu @punnibhai @Hitkul_, FYI. https:...",Tue Dec 25 03:00:21 +0000 2018,2,1,NaN
388,RT @iiit_hyderabad: KCIS Distinguished Lecture...,Mon Dec 24 07:39:21 +0000 2018,0,11,NaN
389,RT @StanfordAILab: Our latest blog post is out...,Fri Dec 21 03:50:39 +0000 2018,0,32,NaN
390,"RT @medialab: In two new papers, @PratikShahPh...",Thu Dec 20 18:05:35 +0000 2018,0,8,NaN
391,RT @RatnRajiv: Wonderful get together with our...,Thu Dec 20 06:14:52 +0000 2018,0,3,NaN
392,@ACMMM19 is the premier international conferen...,Wed Dec 19 02:16:31 +0000 2018,2,3,NaN
393,Feel free to contact us if you have any query ...,Tue Dec 18 14:42:27 +0000 2018,3,2,NaN
394,@NilayShri @RatnRajiv @ACMMM19 Looking forward...,Tue Dec 18 14:27:12 +0000 2018,3,0,NaN
395,"@midasIIITD head, Dr. @RatnRajiv appointed as ...",Tue Dec 18 14:15:32 +0000 2018,12,5,NaN
396,@ACMMM19 @the_dhumketu fill the volunteer form...,Tue Dec 18 12:34:10 +0000 2018,1,0,NaN
397,RT @ACMMM19: New in 2019! Volunteer to serve a...,Tue Dec 18 12:33:42 +0000 2018,0,7,NaN
398,RT @IIITDelhi: Congratulations! authors Yaman ...,Tue Dec 18 04:38:35 +0000 2018,0,3,NaN
399,Best wishes to @midasIIITD students @_himanshu...,Mon Dec 17 16:57:00 +0000 2018,14,4,NaN